name: PHP Linter

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Lint PHP | WordPress Coding Standards
      uses: next-press/github-actions-linters/actions/phpcs@master